数据集剖析指标添加行总数
byzer-org/byzer-extension pull request #100
Opened 2023-03-24 01:54 UTC by ff429452247

## 背景
数据集剖析新增一个行总数指标提供给用户查看整体数据的数量大小

## 预期收益
用户可以直观的查看数据集的数量大小

## 变更点
类：SQLDataSummaryV2
方法：dataFormat、processSelectedMetrics、train
新增方法：getTotalCount

## 技术设计
数据集行数代码中本来就有统计，新增数据集总数指标返回

## 兼容性
不存在兼容性问题

2023-03-24 02:15 UTC, hellozepp requested changes

2023-03-24 02:15 UTC, hellozepp commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLDataSummaryV2.scala
>      if (smallDatasetAccurately) {
如果totalCount、smallDatasetAccurately用户没有指定，那么df.count()是没必要计算的，请修改该逻辑

2023-03-24 02:15 UTC, hellozepp commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLDataSummaryV2.scala
> +      "totalCount" -> getTotalCount(schema, total)
请添加计算totalCount的单例测试

2023-03-24 05:48 UTC, hellozepp commented
LGTM @allwefantasy

2023-03-25 04:07 UTC, allwefantasy approved these changes

2023-03-25 04:08 UTC, merged