#27 add pattern distribution ET
byzer-org/byzer-extension pull request #32
Opened 2022-07-20 06:03 UTC by ckeys

2022-07-20 09:47 UTC, hellozepp commented
#32 improve it

2022-07-22 08:09 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (num_ch_lower == 0 && freq_map.get("a").get != 0)
"a"， "A"， "9" 这些多次用到的定义成常量吧

2022-07-22 08:13 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (freq_map.get("A").get != 0) {
freq_map.get("A").get != 0 和 res = freq_map.get("A").get 可以优化成只调用freq_map.get一次

2022-07-22 08:19 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +        num_ch_lower += 1
find_patterns 里面的判断逻辑这里可以考虑复用吗

2022-07-22 08:21 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    var pattern_func1 = udf(find_alternativePatterns(_))
rename  pattern_func and pattern_func1

2022-07-22 08:34 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +      sc.dataType match {
这里的逻辑是把一个dataframe 拆成n个dataframe（每个dataframe一个列），再来操作吗？有看过这里的执行计划里面，数据load了1遍还是n遍吗

2022-07-22 08:58 UTC, fishcus commented on mlsql-mllib/src/test/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternSummaryTest.scala
> +          "bvYDeRfGuYajdhTqphPYaAPFmcbbPWHnfnORxjGuOiTqGnKKsQwauvfvzkJnZKohToAHCfFTprgGnzDxNzaXNKmJtzeyAScsuxbaMhcxzg" +
这里造了一个超级长的列，但是没有assert 1000这个阈值是否生效吗？

2022-07-22 09:47 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +  var internal_ch_limit = 1000
已经改成从配置项 Params里获取

2022-07-22 09:49 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (freq_map.get("A").get != 0) {
scala里的mutable.map.get获取到的是一个Option值,所以需要再一次 get， 不知道是不是我使用有误

2022-07-22 10:17 UTC, ckeys commented on mlsql-mllib/src/test/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternSummaryTest.scala
> +          "bvYDeRfGuYajdhTqphPYaAPFmcbbPWHnfnORxjGuOiTqGnKKsQwauvfvzkJnZKohToAHCfFTprgGnzDxNzaXNKmJtzeyAScsuxbaMhcxzg" +
我把结果的1000个pattern放在assert里了，所以理论上来说是能检验生效与否

2022-07-22 10:18 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +      sc.dataType match {
这个没看过，怎么去check呢

2022-07-22 10:18 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +          val pattern_group_df = res.groupBy(col("pattern"), col("alternativePattern")).count().orderBy(desc("count")).withColumn("ratio", col("count") / rows_num.toDouble)
DONE

2022-07-22 10:19 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    var pattern_func1 = udf(find_alternativePatterns(_))
DONE

2022-07-22 10:19 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +        num_ch_lower += 1
DONE

2022-07-22 10:19 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (num_ch_lower == 0 && freq_map.get("a").get != 0)
DONE

2022-07-22 10:20 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +  var internal_ch_limit = 1000
DONE

2022-07-23 08:28 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +      sc.dataType match {
从spark ui上看具体的执行计划

2022-07-23 08:33 UTC, fishcus commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (freq_map.get("A").get != 0) {
我指的不是Option.get， 我是说 freq_map.get("A") 这个操作，其实这里在有值的情况下  被调用了3次， 如果freq_map.get("A")第一次调用的时候声明了一个变量，那后面2次可以直接使用这个变量来进行操作，而不是每次都需要从map里面get出来

2022-07-25 02:42 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (freq_map.get("A").get != 0) {
DONE

2022-07-25 02:52 UTC, ckeys commented on mlsql-mllib/src/test/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternSummaryTest.scala
> +          "bvYDeRfGuYajdhTqphPYaAPFmcbbPWHnfnORxjGuOiTqGnKKsQwauvfvzkJnZKohToAHCfFTprgGnzDxNzaXNKmJtzeyAScsuxbaMhcxzg" +
DONE

2022-07-27 07:06 UTC, fishcus approved these changes

2022-07-27 07:43 UTC, hellozepp requested changes

2022-07-27 07:43 UTC, hellozepp commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (freq_map.get("A").get != 0) {
Option请结合Some None使用，参考我的课件https://github.com/hellozepp/scalaTest/blob/master/src/main/src/myscala/basic/HighOrderFunction.scala:33

2022-07-27 07:48 UTC, hellozepp commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    var num_ch_lower = 0
相同含义的一组可以采用组合赋值，参考src/main/liao/bestpractice/Assinment_Internals.scala:7

2022-07-27 07:51 UTC, hellozepp commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (res.length > 1000)
多行if请添加大括号

2022-07-27 07:51 UTC, hellozepp commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +  setDefault(limit_num, "100")
这里的setDefault请放到limit_num字段定义下面

2022-07-27 08:04 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +  setDefault(limit_num, "100")
DONE

2022-07-27 08:08 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (res.length > 1000)
这个不是多行if，这是相当于三目运算

2022-07-27 09:25 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (freq_map.get("A").get != 0) {
DONE

2022-07-27 09:25 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    if (res.length > 1000)
DONE

2022-07-27 09:25 UTC, ckeys commented on mlsql-mllib/src/main/java/tech/mlsql/plugins/mllib/ets/fe/SQLPatternDistribution.scala
> +    var num_ch_lower = 0
DONE

2022-07-27 09:26 UTC, hellozepp approved these changes

2022-07-27 09:26 UTC, merged