Add MessageReplaceRender
byzer-org/byzer-extension pull request #47
Opened 2022-08-10 17:29 UTC by chncaesar

## Changes in this PR.

 [ 需求 ](https://github.com/byzer-org/byzer-lang/issues/1806)  的外置插件。负责匹配正则并替换错误消息。

2022-08-11 03:59 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRenderApp.scala
> +    AppRuntimeStore.store.registerExceptionRender("MessageReplaceRender", classOf[ExceptionReplaceRender].getName)
MessageReplaceRender -> ExceptionReplaceRender ?

2022-08-11 05:39 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +      log.warn("$BYZER_HOME is not set, unable to read err-msg-template.json")
err-msg-template.json 启动时加载到内存就行了吧？ 不需要每次都读

2022-08-11 05:40 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +          .map(  r => Pattern.compile(r.regexp) -> r.msg )
code format

2022-08-11 05:41 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +class ExceptionReplaceRender extends ExceptionRender with Logging with SparkOperationUtil {
需要UT

2022-08-11 05:45 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +    if( showStack ) matchExp.get().get + System.lineSeparator() + LogUtils.format_exception(e)
format之后不对matchExp 做remove吗？

2022-08-11 06:49 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +        matchExp.set( Some( m._2) )
这里用matchExp 最后的值是不是会是随机的啊？ 存在多个match的情况时

2022-08-11 08:42 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +    if( showStack ) matchExp.get().get + System.lineSeparator() + LogUtils.format_exception(e)
Good point.

2022-08-11 08:46 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +    if( showStack ) matchExp.get().get + System.lineSeparator() + LogUtils.format_exception(e)
Good point.

2022-08-11 08:46 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +        matchExp.set( Some( m._2) )
嗯。看了 exists() 函数的代码，确认在第一个匹配时，立即结束循环。所以，不会有随机的值出现。谢谢锋哥细致的review

2022-08-12 09:36 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRenderApp.scala
> +    AppRuntimeStore.store.registerExceptionRender("MessageReplaceRender", classOf[ExceptionReplaceRender].getName)
done

2022-08-12 10:36 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +      log.warn("$BYZER_HOME is not set, unable to read err-msg-template.json")
fixed

2022-08-12 10:36 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +          .map(  r => Pattern.compile(r.regexp) -> r.msg )
fixed

2022-08-12 10:37 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +class ExceptionReplaceRender extends ExceptionRender with Logging with SparkOperationUtil {
done

2022-08-12 11:02 UTC, allwefantasy requested changes
需要有个 .repo 目录，里面带上一些模板信息，参考其他插件项目。

2022-08-15 02:35 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +        matchExp.set( Some( m._2) )
这里不是exists的问题  是你遍历的map对象，map的遍历顺序，当配置的规则变了之后，这里遍历的顺序还保续吗？

2022-08-15 02:42 UTC, fishcus commented on byzer-exception-render/src/test/scala/tech/mlsql/test/plugins/render/ExceptionReplaceRenderSuite.scala
> +      assert(render.is_match(e))
这里加一个format之后  matchExp 确保是清空状态的case吧

2022-08-15 02:43 UTC, fishcus commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +        inited = true
初始化完成之后再设置inited = true？

2022-08-15 04:28 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +        matchExp.set( Some( m._2) )
Map 改为 List

2022-08-15 04:30 UTC, chncaesar commented on byzer-exception-render/src/main/scala/tech/mlsql/plugins/render/ExceptionReplaceRender.scala
> +        inited = true
Good point

2022-08-15 06:54 UTC, chncaesar commented on byzer-exception-render/src/test/scala/tech/mlsql/test/plugins/render/ExceptionReplaceRenderSuite.scala
> +      assert(render.is_match(e))
fixed

2022-08-15 07:34 UTC, fishcus approved these changes

2022-09-02 10:37 UTC, merged