增加矩阵图和AUC图
byzer-org/byzer-extension pull request #73
Opened 2022-09-27 03:08 UTC by tangfei-china

> 矩阵图

```yaml
# 输入数据格式
select label,prediction from predict_data as p_data;

# 测试代码
!visualize p_data '''
runtime: 
   env: source activate ray1.13.0
   cache: false  
control:
   ignoreSort: True
fig:
   matrix:
      annot: True
      cmap: "Blues"
      fmt: "d"
      cbar: False     
''';
```
<img width="538" alt="image" src="https://user-images.githubusercontent.com/8468837/192422631-48a4e6e6-aa33-471f-b0bc-451d660a1e3a.png">

> AUC

```yaml
# 输入数据格式，probability是为true的概率数据
select label,vec_array(probability)[1] as probability from predict_data as p_data_auc;

# 测试代码
!visualize p_data_auc '''
runtime: 
   env: source activate ray1.13.0
   cache: false  
control:
   ignoreSort: True
fig:
   auc:
    linewidth: 2
''';
```
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8468837/192422675-b1d68fdd-7bc5-47fc-a743-47ed65522f47.png">

2022-10-11 08:55 UTC, allwefantasy requested changes

2022-10-11 08:55 UTC, allwefantasy commented on byzer-yaml-visualization/src/main/java/tech/mlsql/plugins/visualization/builder.scala
> +    pyLang.raw.code("import matplotlib.pyplot as plt").end
这里是不是可以增加一个控制参数 类似：

```
runtime: 
   env: source /opt/miniconda3/bin/activate ray-1.12.0
   cache: false
control:
   backend: matplotlib 
```
默认是 plotly。 然后根据不同的 backend 来绘制不同的图

2022-10-11 08:55 UTC, allwefantasy commented on byzer-yaml-visualization/src/main/java/tech/mlsql/plugins/visualization/builder.scala
> +    if (plt) {
同理，这部分代码根据不同的 backend 来进行判断执行逻辑

2022-10-11 08:55 UTC, allwefantasy commented on byzer-yaml-visualization/src/main/java/tech/mlsql/plugins/visualization/builder.scala
> +      case "matrix" =>
这部分是不是 backend 应该是 sklearn。 另外，我们还可以根据不同的图类型 比如 fig.martix 则自动设置 backend 为sklearn(如果用户没有显示设置的话)，这样会显得更智能一些。

2022-10-11 09:05 UTC, tangfei-china commented on byzer-yaml-visualization/src/main/java/tech/mlsql/plugins/visualization/builder.scala
> +      case "matrix" =>
谢谢 指导
学习了

2022-10-12 11:05 UTC, allwefantasy approved these changes

2022-10-12 11:05 UTC, merged